- name: Get Vault Creation
  hosts: localhost
  connection: localhost
  tasks:
    - name: Print password
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=test/my_credentials:password token={{ vault_token }} url=http://172.31.81.190:8200 validate_certs=False') }}"