- name: Install Python
  ansible.builtin.dnf:
  name: "{{ item }}"
  state: installed
  loop:
    - python3 
    - gcc 
    - python3-devel

- name: Load app_prerequsites
  ansible.builtin.include_tasks:
    file: app_prerequites.yml

- name: Download the dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt

- name: Load systemd setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml